version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=marat
    volumes: 
      - mongo-data:/data/ca
      - mongo-data:/data/configdb

  mongo-express:
    image: mongo-express
    restart: on-failure:5
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=marat
    depends_on:
      - mongodb

  mongo-app:
    image: mongoapp:staging
    restart: on-failure:5
    ports: 
      - 3000:3000
      - 80:3000
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=marat
    depends_on:
      - mongodb  

volumes:
  mongo-data:
    driver: local



# docker run -d \
#     --name mongodb \
#     --net mongo-net \
#     -e MONGO_INITDB_ROOT_USERNAME=admin \
#     -e MONGO_INITDB_ROOT_PASSWORD=marat \
#     mongo


# docker run -d \
#     -p 8081:8081 \
#     --name mongo-ui \
#     --net mongo-net \
#     -e ME_CONFIG_MONGODB_SERVER=mongodb \
#     -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
#     -e ME_CONFIG_MONGODB_ADMINPASSWORD=marat \
#     mongo-express

